### ISSUE TITLE
BHS-mapping-KJV line missing data

### ISSUE THREAD

**Issue by acsburg** [eliranwong/OpenHebrewBible#1]
This line:
12489	16	7	68	Their horses,〈H5483＝｜｜｜〉 seven〈H7651＝｜｜｜〉 hundred〈H3967＝｜｜｜〉 thirty〈H7970＝｜｜｜〉 and six:〈H8337＝｜｜｜〉 their mules,〈H6505＝｜｜｜〉 two hundred〈H3967＝｜｜｜〉 forty〈H705＝｜｜｜〉 and five:〈H2568＝｜｜｜〉

is missing data within the carats

**Comment by eliranwong** [comment]
Thanks for your message.

You are right, BHSA data does not map a corresponding verse in KJV Neh 7:68.

You may read for a summary of BHSA in KJV versification at:

https://github.com/eliranwong/OpenHebrewBible/blob/master/019-BHSA_to_KJV_versification/Readme.md
